#!/usr/bin/env python3
"""Fetch rendered product (beste-*) pages from the live site into MDX content files.

Product pages are generated by the zb_mp WordPress plugin and are not included in the
WXR export (only the products-review Elementor template is). This script scrapes the
published HTML for each product slug and writes src/content/pages/beste-*.mdx files.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import time
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor, as_completed
from html import unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGES_DIR = ROOT / "src/content/pages"
PRODUCT_HTML_DIR = ROOT / "src/content/product-html"
PUBLIC_IMAGES = ROOT / "public/images"
SITE = os.environ.get("SITE_URL", "https://interieuradviespunt.nl")
WXR_PATH = Path(
    os.environ.get(
        "WXR_PATH",
        "/Users/gauravkashyap/Downloads/interieuradviespunt.WordPress.2026-06-25.xml",
    )
)
SITEMAP_URL = f"{SITE}/zb_mp-sitemap.xml"
USER_AGENT = "InterieuradviespuntMigration/1.0"


def fetch_url(url: str, timeout: int = 60) -> str:
    result = subprocess.run(
        ["curl", "-sfL", "--max-time", str(timeout), url],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise urllib.error.URLError(f"curl failed for {url}: {result.stderr.strip()}")
    return result.stdout


def product_slugs_from_sitemap() -> list[str]:
    xml = fetch_url(SITEMAP_URL)
    root = ET.fromstring(xml)
    ns = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    slugs: set[str] = set()
    for loc in root.findall(".//sm:loc", ns):
        if not loc.text or "/beste-" not in loc.text:
            continue
        slugs.add(loc.text.rstrip("/").split("/")[-1])
    return sorted(slugs)


def product_slugs_from_xml() -> list[str]:
    if not WXR_PATH.exists():
        return []
    text = WXR_PATH.read_text(encoding="utf-8", errors="ignore")
    urls = set(re.findall(r"https://interieuradviespunt\.nl/beste-[a-z0-9\-]+/", text))
    return sorted({u.rstrip("/").split("/")[-1] for u in urls})


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def strip_html(html: str) -> str:
    text = re.sub(r"<[^>]+>", " ", html or "")
    return re.sub(r"\s+", " ", unescape(text)).strip()


def upload_to_local(url: str) -> str:
    if not url or url.startswith("/images/"):
        return url or ""
    if "/wp-content/uploads/" in url:
        rel = url.split("/wp-content/uploads/", 1)[1].split("?")[0]
        return f"/images/{rel}"
    return url


def download_image(url: str, dest: Path) -> bool:
    if dest.exists() and dest.stat().st_size > 0:
        return True
    dest.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        ["curl", "-sfL", url.split("?")[0], "-o", str(dest)],
        capture_output=True,
    )
    return result.returncode == 0 and dest.exists() and dest.stat().st_size > 0


def rewrite_content_html(html: str, image_urls: set[str]) -> str:
    def replace_src(match: re.Match) -> str:
        attr, url = match.group(1), match.group(2)
        if "/wp-content/uploads/" in url:
            full = url if url.startswith("http") else f"{SITE}{url}"
            image_urls.add(full.split("?")[0])
            local = upload_to_local(full)
            return f'{attr}="{local}"'
        if url.startswith(SITE):
            return f'{attr}="{url.replace(SITE, "")}"'
        return match.group(0)

    html = re.sub(r'(src|href)="([^"]+)"', replace_src, html)
    html = re.sub(rf"{re.escape(SITE)}/", "/", html)
    html = re.sub(r'href="/wp-content/uploads/([^"]+)"', r'href="/images/\1"', html)

    # Elementor star icons -> accessible text stars
    html = re.sub(
        r"(?:<i[^>]*>\s*(?:&#xE934;|&#xe934;)\s*</i>\s*){5}\s*5/5",
        '<span class="product-stars" aria-label="5 van 5 sterren">★★★★★</span> 5/5',
        html,
        flags=re.I,
    )
    return html


def extract_page_content(html: str) -> tuple[str, dict]:
    try:
        from bs4 import BeautifulSoup
    except ImportError as exc:
        raise SystemExit("Install beautifulsoup4: pip install beautifulsoup4") from exc

    soup = BeautifulSoup(html, "html.parser")
    header = soup.find("header")
    footer = soup.find("footer")
    content_div = None
    if header:
        for sib in header.next_siblings:
            if sib == footer:
                break
            if getattr(sib, "name", None) == "div" and "elementor" in " ".join(
                sib.get("class", [])
            ):
                content_div = sib
                break

    if not content_div:
        content_div = soup.select_one("div.elementor") or soup.find("main")

    if not content_div:
        raise ValueError("Could not find page content")

    for tag in content_div.find_all(["script", "style", "noscript", "iframe"]):
        tag.decompose()

    meta: dict[str, str] = {}
    og_title = soup.find("meta", property="og:title")
    og_desc = soup.find("meta", property="og:description")
    og_image = soup.find("meta", property="og:image")
    if og_title and og_title.get("content"):
        meta["title"] = strip_html(og_title["content"]).split("|")[0].strip()
    if og_desc and og_desc.get("content"):
        meta["description"] = strip_html(og_desc["content"])[:500]
    h1 = content_div.find("h1")
    if h1 and "title" not in meta:
        meta["title"] = h1.get_text(" ", strip=True)
    if "description" not in meta:
        first_p = content_div.find("p")
        meta["description"] = strip_html(first_p.decode_contents() if first_p else "")[:500]

    if og_image and og_image.get("content"):
        meta["featuredImage"] = upload_to_local(og_image["content"])
    else:
        img = content_div.find("img", src=True)
        if img:
            meta["featuredImage"] = upload_to_local(img["src"])

    modified = content_div.find(string=re.compile(r"Laatst bijgewerkt", re.I))
    if modified:
        match = re.search(r"(\d{1,2}\s+\w+\.?\s+\d{4})", modified)
        if match:
            meta["updatedLabel"] = match.group(1)

    published = content_div.find(string=re.compile(r"Gepubliceerd op", re.I))
    if published:
        match = re.search(r"(\d{1,2}\s+\w+\.?\s+\d{4})", published)
        if match:
            meta["publishedLabel"] = match.group(1)

    body_html = str(content_div)
    return body_html, meta


def escape_mdx(html: str) -> str:
    return html.replace("{", "\\{").replace("}", "\\}")


def write_product_mdx(slug: str, meta: dict, body_html: str) -> None:
    title = meta.get("title") or slug.replace("-", " ").title()
    description = meta.get("description") or f"Top 10 {title} op Interieuradviespunt.nl"
    featured = meta.get("featuredImage") or "/images/2023/05/wanddecoratie.jpg"

    PRODUCT_HTML_DIR.mkdir(parents=True, exist_ok=True)
    (PRODUCT_HTML_DIR / f"{slug}.html").write_text(body_html, encoding="utf-8")

    lines = [
        "---",
        f"title: {yaml_quote(title[:200])}",
        f"description: {yaml_quote(description[:500])}",
        f"featuredImage: {yaml_quote(featured)}",
        'pageType: "product"',
    ]
    if meta.get("updatedLabel"):
        lines.append(f"updatedLabel: {yaml_quote(meta['updatedLabel'])}")
    if meta.get("publishedLabel"):
        lines.append(f"publishedLabel: {yaml_quote(meta['publishedLabel'])}")
    lines.extend(["---", ""])
    lines.append(f"Product review: [{title}](/{slug}/).")
    lines.append("")

    path = PAGES_DIR / f"{slug}.mdx"
    path.write_text("\n".join(lines), encoding="utf-8")


def fetch_product(slug: str) -> dict:
    url = f"{SITE}/{slug}/"
    html = fetch_url(url)
    image_urls: set[str] = set()
    body_html, meta = extract_page_content(html)
    body_html = rewrite_content_html(body_html, image_urls)
    write_product_mdx(slug, meta, body_html)
    return {"slug": slug, "title": meta.get("title"), "images": len(image_urls), "ok": True}


def download_images(image_urls: set[str]) -> int:
    jobs = []
    for url in sorted(image_urls):
        if "/wp-content/uploads/" not in url:
            continue
        rel = url.split("/wp-content/uploads/", 1)[1]
        jobs.append((url, PUBLIC_IMAGES / rel))

    success = 0
    with ThreadPoolExecutor(max_workers=8) as pool:
        futures = {pool.submit(download_image, url, dest): dest for url, dest in jobs}
        for future in as_completed(futures):
            if future.result():
                success += 1
    return success


def main() -> None:
    sitemap_slugs = product_slugs_from_sitemap()
    xml_slugs = product_slugs_from_xml()
    slugs = sorted(set(sitemap_slugs) | set(xml_slugs))
    slugs = [s for s in slugs if s.startswith("beste-")]

    print(f"Fetching {len(slugs)} product pages from {SITE}...")
    PAGES_DIR.mkdir(parents=True, exist_ok=True)

    # Remove old product MDX files before re-fetch
    for old in PAGES_DIR.glob("beste-*.mdx"):
        old.unlink()

    results = []
    failed = []
    all_image_urls: set[str] = set()

    for i, slug in enumerate(slugs, 1):
        try:
            url = f"{SITE}/{slug}/"
            html = fetch_url(url)
            body_html, meta = extract_page_content(html)
            image_urls: set[str] = set()
            body_html = rewrite_content_html(body_html, image_urls)
            all_image_urls |= image_urls
            write_product_mdx(slug, meta, body_html)
            results.append(slug)
            print(f"  [{i}/{len(slugs)}] {slug} — {meta.get('title', '')[:60]}")
            time.sleep(0.15)
        except Exception as exc:
            failed.append({"slug": slug, "error": str(exc)})
            print(f"  [{i}/{len(slugs)}] FAILED {slug}: {exc}")

    print(f"\nDownloaded content for {len(results)}/{len(slugs)} pages")
    if failed:
        print(f"Failed: {len(failed)}")

    print(f"Downloading images ({len(all_image_urls)})...")
    img_ok = download_images(all_image_urls)
    print(f"Images: {img_ok}/{len(all_image_urls)}")

    summary = {
        "products": len(results),
        "failed": len(failed),
        "images": img_ok,
        "slugs": results,
    }
    (ROOT / "product-fetch-summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(json.dumps({"products": len(results), "failed": len(failed), "images": img_ok}, indent=2))


if __name__ == "__main__":
    main()
